//showing all products in home pag.
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST' ;
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS' ;
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL' ;

//single product
export const PRODUCT_DEFAULT_REQUEST = 'PRODUCT_DEFAULT_REQUEST' ;
export const PRODUCT_DEFAULT_SUCCESS = 'PRODUCT_DEFAULT_SUCCESS' ;
export const PRODUCT_DEFAULT_FAIL = 'PRODUCT_DEFAULT_FAIL' ;


//add to cart 
export const ADD_TO_CART = "ADD_TO_CART" ;


//cart remove
export const CART_REMOVE = "CART_REMOVE" ;


//signin variables :
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

//signup variables :
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';


export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

//cart variables
export const CART_EMPTY = 'CART_EMPTY';

//order variables
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

//user variables
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';

//user updating
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';